server:
  port: 8100

spring:
  application:
    name: cambio-service

  datasource:
    url: jdbc:postgresql://localhost:5433/micro-service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

flyway:
  locations:
    - classpath:/db_migration